# Generated by Django 5.0.2 on 2026-02-23 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='api_user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='api_user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='iihf_logo/')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cups',
                'ordering': ['-year'],
                'indexes': [models.Index(fields=['year'], name='cups_year_0195ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_a', models.IntegerField(blank=True, null=True)),
                ('score_b', models.IntegerField(blank=True, null=True)),
                ('score_a_final', models.IntegerField(blank=True, null=True)),
                ('score_b_final', models.IntegerField(blank=True, null=True)),
                ('overtime', models.BooleanField(default=False)),
                ('shootout', models.BooleanField(default=False)),
                ('date', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.cup')),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['date', 'team_a__group'],
            },
        ),
        migrations.CreateModel(
            name='MatchTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_a', models.IntegerField(blank=True, null=True)),
                ('score_b', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='api.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_tips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_tips',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='team_flags/')),
                ('gp', models.IntegerField(default=0)),
                ('win', models.IntegerField(default=0)),
                ('los', models.IntegerField(default=0)),
                ('wot', models.IntegerField(default=0)),
                ('lot', models.IntegerField(default=0)),
                ('gf', models.IntegerField(default=0)),
                ('ga', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('year', models.IntegerField(db_index=True)),
                ('group', models.CharField(default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.cup')),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='SpecialTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czech_shooter_first', models.CharField(blank=True, max_length=64)),
                ('czech_shooter_last', models.CharField(blank=True, max_length=64)),
                ('max_goals_per_game', models.IntegerField(default=0)),
                ('overtimes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_tips', to='api.cup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_tips', to=settings.AUTH_USER_MODEL)),
                ('bronze_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bronze_a_tips', to='api.team')),
                ('bronze_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bronze_b_tips', to='api.team')),
                ('final_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_a_tips', to='api.team')),
                ('final_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_b_tips', to='api.team')),
                ('group_a_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_a_1_tips', to='api.team')),
                ('group_a_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_a_2_tips', to='api.team')),
                ('group_a_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_a_3_tips', to='api.team')),
                ('group_a_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_a_4_tips', to='api.team')),
                ('group_b_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_b_1_tips', to='api.team')),
                ('group_b_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_b_2_tips', to='api.team')),
                ('group_b_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_b_3_tips', to='api.team')),
                ('group_b_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_b_4_tips', to='api.team')),
                ('team_drop_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drop_a_tips', to='api.team')),
                ('team_drop_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drop_b_tips', to='api.team')),
                ('team_first_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_goal_tips', to='api.team')),
                ('team_last_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_goal_tips', to='api.team')),
                ('team_least_goals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='least_goals_tips', to='api.team')),
                ('team_most_goals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='most_goals_tips', to='api.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_tips', to='api.team')),
            ],
            options={
                'db_table': 'special_tips',
            },
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czech_shooter_first', models.CharField(blank=True, max_length=64)),
                ('czech_shooter_last', models.CharField(blank=True, max_length=64)),
                ('max_goals_per_game', models.IntegerField(default=0)),
                ('overtimes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_results', to='api.cup')),
                ('bronze_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bronze_a_results', to='api.team')),
                ('bronze_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bronze_b_results', to='api.team')),
                ('final_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_a_results', to='api.team')),
                ('final_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_b_results', to='api.team')),
                ('group_a_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_a_1_results', to='api.team')),
                ('group_a_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_a_2_results', to='api.team')),
                ('group_a_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_a_3_results', to='api.team')),
                ('group_a_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_a_4_results', to='api.team')),
                ('group_b_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_b_1_results', to='api.team')),
                ('group_b_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_b_2_results', to='api.team')),
                ('group_b_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_b_3_results', to='api.team')),
                ('group_b_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_b_4_results', to='api.team')),
                ('team_drop_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_a_results', to='api.team')),
                ('team_drop_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_b_results', to='api.team')),
                ('team_first_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_goal_results', to='api.team')),
                ('team_last_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_goal_results', to='api.team')),
                ('team_least_goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='least_goals_results', to='api.team')),
                ('team_most_goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='most_goals_results', to='api.team')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_tournaments', to='api.team')),
            ],
            options={
                'db_table': 'special_results',
            },
        ),
        migrations.CreateModel(
            name='Playoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playoff_type', models.CharField(choices=[('QFA1', 'QFA1'), ('QFA2', 'QFA2'), ('QFB1', 'QFB1'), ('QFB2', 'QFB2'), ('SFA', 'SFA'), ('SFB', 'SFB'), ('BMG', 'BMG'), ('GMG', 'GMG')], db_index=True, max_length=4)),
                ('score_a', models.IntegerField(blank=True, null=True)),
                ('score_b', models.IntegerField(blank=True, null=True)),
                ('score_a_final', models.IntegerField(blank=True, null=True)),
                ('score_b_final', models.IntegerField(blank=True, null=True)),
                ('overtime', models.BooleanField(default=False)),
                ('shootout', models.BooleanField(default=False)),
                ('date', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playoffs', to='api.cup')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playoffs_as_team_a', to='api.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playoffs_as_team_b', to='api.team')),
            ],
            options={
                'db_table': 'playoffs',
                'ordering': ['date', 'playoff_type'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_a', to='api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_b', to='api.team'),
        ),
        migrations.CreateModel(
            name='UserPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('part', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_points', to='api.cup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_points',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'),
        ),
        migrations.AddIndex(
            model_name='matchtip',
            index=models.Index(fields=['user', 'match'], name='match_tips_user_id_e7549a_idx'),
        ),
        migrations.AddIndex(
            model_name='matchtip',
            index=models.Index(fields=['match'], name='match_tips_match_i_be70da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matchtip',
            unique_together={('match', 'user')},
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['year', 'group'], name='teams_year_09ce5f_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['cup', 'group'], name='teams_cup_id_d50fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['-points', 'name'], name='teams_points_ffbdd0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'year', 'cup')},
        ),
        migrations.AddIndex(
            model_name='specialtip',
            index=models.Index(fields=['user', 'cup'], name='special_tip_user_id_71759b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='specialtip',
            unique_together={('user', 'cup')},
        ),
        migrations.AddIndex(
            model_name='playoff',
            index=models.Index(fields=['cup', 'date'], name='playoffs_cup_id_3faa16_idx'),
        ),
        migrations.AddIndex(
            model_name='playoff',
            index=models.Index(fields=['playoff_type'], name='playoffs_playoff_650d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['cup', 'date'], name='matches_cup_id_5f2940_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['team_a', 'team_b'], name='matches_team_a__f834e3_idx'),
        ),
        migrations.AddIndex(
            model_name='userpoint',
            index=models.Index(fields=['user', 'cup', 'part'], name='user_points_user_id_22e8c1_idx'),
        ),
        migrations.AddIndex(
            model_name='userpoint',
            index=models.Index(fields=['cup', 'part', '-points'], name='user_points_cup_id_d3fad7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpoint',
            unique_together={('user', 'cup', 'part')},
        ),
    ]
