# Generated by Django 5.0.2 on 2024-02-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='team_flags/')),
                ('gp', models.IntegerField(default=0)),
                ('win', models.IntegerField(default=0)),
                ('los', models.IntegerField(default=0)),
                ('wot', models.IntegerField(default=0)),
                ('lot', models.IntegerField(default=0)),
                ('gf', models.IntegerField(default=0)),
                ('ga', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
