# Generated by Django 5.0.2 on 2024-02-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iihf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
