# Generated by Django 5.0.2 on 2024-02-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iihf', '0003_cup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='year',
            field=models.IntegerField(default=2024, unique=True),
        ),
    ]
