# Generated by Django 5.0.2 on 2024-02-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iihf', '0004_alter_cup_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cup',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cup',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cup',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='iihf_logo/'),
        ),
    ]
