# Generated by Django 5.0.2 on 2024-02-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iihf', '0007_match_cup'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='group',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
