# Generated by Django 5.0.2 on 2024-04-19 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iihf', '0013_specialtip_cup_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialtip',
            name='bronze_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bronze_a_special_tips', to='iihf.team'),
        ),
        migrations.AlterField(
            model_name='specialtip',
            name='bronze_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bronze_b_special_tips', to='iihf.team'),
        ),
    ]
