# Generated by Django 5.0.2 on 2024-04-19 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iihf', '0014_alter_specialtip_bronze_a_alter_specialtip_bronze_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialtip',
            name='final_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_a_special_tips', to='iihf.team'),
        ),
        migrations.AlterField(
            model_name='specialtip',
            name='final_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_b_special_tips', to='iihf.team'),
        ),
        migrations.AlterField(
            model_name='specialtip',
            name='group_a_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_a_1_special_tips', to='iihf.team'),
        ),
        migrations.AlterField(
            model_name='specialtip',
            name='group_a_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_a_2_special_tips', to='iihf.team'),
        ),
        migrations.AlterField(
            model_name='specialtip',
            name='group_a_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_a_3_special_tips', to='iihf.team'),
        ),
        migrations.AlterField(
            model_name='specialtip',
            name='group_a_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_a_4_special_tips', to='iihf.team'),
        ),
        migrations.AlterField(
            model_name='specialtip',
            name='group_b_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_b_1_special_tips', to='iihf.team'),
        ),
        migrations.AlterField(
            model_name='specialtip',
            name='group_b_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_b_2_special_tips', to='iihf.team'),
        ),
        migrations.AlterField(
            model_name='specialtip',
            name='group_b_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_b_3_special_tips', to='iihf.team'),
        ),
        migrations.AlterField(
            model_name='specialtip',
            name='group_b_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_b_4_special_tips', to='iihf.team'),
        ),
        migrations.AlterField(
            model_name='specialtip',
            name='team_drop_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_drop_a_special_tips', to='iihf.team'),
        ),
        migrations.AlterField(
            model_name='specialtip',
            name='team_drop_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_drop_b_special_tips', to='iihf.team'),
        ),
        migrations.AlterField(
            model_name='specialtip',
            name='team_first_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_first_goal_special_tips', to='iihf.team'),
        ),
        migrations.AlterField(
            model_name='specialtip',
            name='team_last_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_last_goal_special_tips', to='iihf.team'),
        ),
        migrations.AlterField(
            model_name='specialtip',
            name='team_least_goals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_least_goals_special_tips', to='iihf.team'),
        ),
        migrations.AlterField(
            model_name='specialtip',
            name='team_most_goals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_most_goals_special_tips', to='iihf.team'),
        ),
        migrations.AlterField(
            model_name='specialtip',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_special_tips', to='iihf.team'),
        ),
    ]
