# Generated by Django 5.0.2 on 2024-04-19 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iihf', '0015_alter_specialtip_final_a_alter_specialtip_final_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialtip',
            name='cup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cup', to='iihf.cup'),
        ),
    ]
