# Generated by Django 5.0.2 on 2024-04-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iihf', '0016_alter_specialtip_cup'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score_a_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score_b_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='ot',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='so',
            field=models.CharField(blank=True, null=True),
        ),
    ]
