# Generated by Django 5.0.2 on 2024-04-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iihf', '0017_match_score_a_final_match_score_b_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='so',
        ),
    ]
