# Generated by Django 5.0.2 on 2024-04-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iihf', '0019_remove_match_ot'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='overtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='shootout',
            field=models.BooleanField(default=False),
        ),
    ]
