# Generated by Django 5.0.2 on 2024-04-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iihf', '0021_userpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoint',
            name='part',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
