# Generated by Django 5.0.2 on 2025-05-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iihf', '0024_alter_specialtip_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtip',
            name='score_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchtip',
            name='score_b',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
